### ISSUE TITLE
Blob Build doesn't support Paper Plugins

### ISSUE THREAD

**Issue by vitekform** [WalshyDev/blob-builds#39]
So there are 2 types of plugins. Bukkit plugins using normal plugin.yml and plugins for Paper (and its forks) which uses paper-plugin.yml (and also Brigadier API). Blob Build doesn't support paper plugins and it just outputs: {"success":false,"code":1004,"error":"plugin.yml not found"}.

**Comment by WalshyDev** [comment]
Should now be supported, let me know if there's any issues :)
